version: '3.8'

services:
  nasbot:
    image: ghcr.io/fabbro96/nasbot:latest
    container_name: nasbot
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    pid: "host"
    volumes:
      - ./config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev:ro
      - /sys:/sys:ro
      - /:/hostfs:ro # Useful if it needs to monitor host root FS space
