import re

en_keys = """
		"type_time_prompt":            "Please type the new time (e.g. 14:30):",
		"cancel":                      "❌ Cancel",
		"good_afternoon":              "Good afternoon! ☕",
		"report_next_date":            "\\n📨 _Next report: %02d %s %02d:%02d_",
		"wol_settings_title":          "💻 *Wake-on-LAN (WOL)*\\n\\nEnter the MAC Address of the computer you want to wake up using the `/wake` command.",
		"wol_current_none":            "\\n\\nCurrently: _Not configured_",
		"wol_current_mac":             "\\n\\nCurrently: `%s`",
		"wol_btn_edit":                "📝 Edit MAC",
		"wol_prompt":                  "💻 Enter the new MAC Address (e.g. `AA:BB:CC:DD:EE:FF`):",
		"backup_settings_title":       "📦 *Backup Configuration*\\n\\nSelect the Telegram User ID (Chat ID) where backups generated by `/backup` will be sent.",
		"backup_current_default":      "\\n\\nCurrently: _Default_ (`%d`)",
		"backup_current_uid":          "\\n\\nCurrently: `%d`",
		"backup_btn_edit":             "📝 Edit Target ID",
		"backup_prompt":               "📦 Enter the Telegram User ID (Chat ID) to receive backups:",
		"ai_gathering_context":        "⏳ Gathering context (syslog, top, docker stats) and asking AI...",
		"mac_manual_btn":              "✍️ Manual Entry",
		"mac_select_prompt":           "💻 Select a device from the network or enter manually:",
"""

it_keys = """
		"type_time_prompt":            "Scrivi il nuovo orario (es. 14:30):",
		"cancel":                      "❌ Annulla",
		"good_afternoon":              "Buon pomeriggio! ☕",
		"report_next_date":            "\\n📨 _Prossimo report: %02d %s %02d:%02d_",
		"wol_settings_title":          "💻 *Wake-on-LAN (WOL)*\\n\\nInserisci il MAC Address del computer che vuoi accendere usando il comando `/wake`.",
		"wol_current_none":            "\\n\\nAttualmente: _Non configurato_",
		"wol_current_mac":             "\\n\\nAttualmente: `%s`",
		"wol_btn_edit":                "📝 Modifica MAC",
		"wol_prompt":                  "💻 Inserisci il nuovo MAC Address (es. `AA:BB:CC:DD:EE:FF`):",
		"backup_settings_title":       "📦 *Backup Configurazioni*\\n\\nSeleziona il Telegram User ID (Chat ID) a cui verranno inviati i backup generati col comando `/backup`.",
		"backup_current_default":      "\\n\\nAttualmente: _Default_ (`%d`)",
		"backup_current_uid":          "\\n\\nAttualmente: `%d`",
		"backup_btn_edit":             "📝 Modifica ID Destinatario",
		"backup_prompt":               "📦 Inserisci il Telegram User ID (Chat ID) a cui inviare i backup:",
		"ai_gathering_context":        "⏳ Sto raccogliendo il contesto (syslog, top, docker stats) e chiedendo all'AI...",
		"mac_manual_btn":              "✍️ Inserimento Manuale",
		"mac_select_prompt":           "💻 Seleziona un dispositivo in rete o inserisci a mano:",
"""

with open('internal/app/translations.go', 'r') as f:
    content = f.read()

# For each language block ending with `	},`, insert the keys
languages = ['"en": {', '"it": {', '"es": {', '"de": {', '"zh": {', '"uk": {']
for lang in languages:
    idx = content.find(lang)
    if idx == -1: continue
    
    # Find the end of this block
    end_idx = content.find('	},', idx)
    
    keys_to_insert = it_keys if lang == '"it": {' else en_keys
    
    content = content[:end_idx] + keys_to_insert + content[end_idx:]

with open('internal/app/translations.go', 'w') as f:
    f.write(content)

